pull_request_rules:
  - name: auto-approve
    conditions: [base=main]
    actions:
      review:
        type: APPROVE
        message: "auto-approved via bot_account"
        bot_account: decobber2
