queue_rules:
  - name: default
    merge_conditions: []
    branch_protection_injection_mode: none
pull_request_rules:
  - name: automerge
    conditions: [label=automerge]
    actions:
      queue:
        name: default
